### ISSUE TITLE
Bug: Crash when opening chest on multiplayer server

### ISSUE THREAD

**Issue by Proxi2** [Aguga2201/ChestLogs#4]
When opening a chest on a server, both when the server has the mod installed and not installed, the client will crash. Here is the error: https://mclo.gs/TaRJOdK

The server log doesn't show anything. Just that the client disconnected

**Comment by Aguga2201** [comment]
Does the client have the mod installed? If so, remove it. It should only be on the server.

**Comment by Proxi2** [comment]
Ah thats my bad. I'm dumb. Looking back on the modrinth listing I see it says server and not client/server. Thank you
